name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Build
        working-directory: ./source
        run: dotnet build Handlebars.sln -c Release
  
  test-windows:
    name: Tests on Windows
    runs-on: windows-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Test
        working-directory: ./source
        run: dotnet test Handlebars.sln --logger:trx

  test-linux-netcoreapp-31:
    runs-on: ubuntu-latest
    needs: [build]
    name: Tests on Linux (.NET Core 3.1.102)
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Test
        working-directory: ./source
        run: dotnet test Handlebars.Test/Handlebars.Test.csproj -f netcoreapp3.1 --logger:trx

  test-macos-netcoreapp-31:
    runs-on: macos-latest
    needs: [build]
    name: Tests on MacOS (.NET Core 3.1.102)
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Test
        working-directory: ./source
        run: dotnet test Handlebars.Test/Handlebars.Test.csproj -f netcoreapp3.1 --logger:trx
        
  sonar-pr:
    name: SonarCloud
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build source/Handlebars.sln -c Release
        testCommand: dotnet test source/Handlebars.sln --logger:trx --collect:"XPlat Code Coverage" --settings source/Handlebars.Test/coverlet.runsettings
        projectKey: Handlebars-Net_Handlebars.Net
        projectName: Handlebars.Net
        sonarOrganisation: handlebars-net
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths="**/*.opencover.xml"
            /d:sonar.cs.vstest.reportsPaths="**/*.trx"
            /d:sonar.coverage.exclusions="**/*.md;source/Handlebars.Benchmark/**/*.*"
            /d:sonar.pullrequest.key=${{ github.event.number }}
            /d:sonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            /d:sonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
      env:
        SONAR_TOKEN: ee613b797cee47bc17202bcf9bc04b44d8a44e1b
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
