name: Pull Request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Build
        working-directory: ./source
        run: dotnet build Handlebars.Code.sln -c Release
  
  test-windows:
    runs-on: windows-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Test
        working-directory: ./source
        run: dotnet test ./Handlebars.Test/Handlebars.Test.csproj -f netcoreapp3.1 --logger:trx

  test-linux:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Test
        working-directory: ./source
        run: dotnet test ./Handlebars.Test/Handlebars.Test.csproj -f netcoreapp3.1 --logger:trx
        
  test-macos:
    runs-on: macos-latest
    needs: [build]
    steps:
      - uses: actions/checkout@master
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.102
      - name: Test
        working-directory: ./source
        run: dotnet test ./Handlebars.Test/Handlebars.Test.csproj -f netcoreapp3.1 --logger:trx
  
  sonar-pr:
    runs-on: windows-latest
    needs: [build]
    steps:
    - uses: actions/checkout@v2
    - name: Sonarscanner for dotnet
      uses: Secbyte/dotnet-sonarscanner@v2.2
      with:
        buildCommand: dotnet build source/Handlebars.Code.sln -f netstandard2.0 -c Release
        testCommand: dotnet test source/Handlebars.Test/Handlebars.Test.csproj -f netcoreapp3.1 --logger:trx --collect "code coverage" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
        projectKey: zjklee_handlebars.csharp
        projectName: handlebars.csharp
        sonarOrganisation: zjklee
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths="**/*.opencover.xml"
            /d:sonar.cs.vstest.reportsPaths="**/*.trx"
            /d:sonar.coverage.exclusions="**/*.cs","**/*.md"
            /d:sonar.pullrequest.key=${{ github.event.number }}
            /d:sonar.pullrequest.branch=${{ github.event.pull_request.head.ref }}
            /d:sonar.pullrequest.base=${{ github.event.pull_request.base.ref }}
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
